###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-16 00:22:51
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-09-16 00:23:05
###############################################################


invokables:
	student_data_fieldset_form : Data/Form/StudentDataFieldsetForm
	student_data_create_form : Data/Form/StudentDataCreateForm
	student_data_edit_form : Data/Form/StudentDataEditForm
	student_data_search_form : Data/Form/StudentDataSearchForm